/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onlineassessment;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Enumeration;
import java.util.Random;
import javax.swing.AbstractButton;
import javax.swing.JRadioButton;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import javax.swing.Timer;


/**
 *
 * @author mohan
 */
public class WelcomeStudent extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeStudent
     */
    static int apteasy_id=0;
    static int aptmedium_id=1;
    static int apthard_id=0;
    static int techeasy_id=0;
    static int techmedium_id=1;
    static int techhard_id=0;
    static int reaeasy_id=0;
    static int reamedium_id=1;
    static int reahard_id=0;
    static int level=0;
    static String type;
    static String selected;
    static int id=0;
    String que_type="null";
    static  String q,a,b,c,d;
    String user;
    static int number=0;
    static String cor="null";
    static int score=0;
    Connection con=null;
   Statement st;
   ResultSet rs;
 Timer t,t1;
    public WelcomeStudent() {
        initComponents();
        setLocationRelativeTo(this);
    }
      public void close1(){
 
 WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
 Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
 
 }
      public void setUsername(String user)
      {
          this.user=user;
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        myGroup1 = new javax.swing.ButtonGroup();
        myGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Welcome Student");

        jPanel2.setBackground(new java.awt.Color(84, 114, 113));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 500));

        myGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(25, 18, 18));
        jRadioButton1.setText("Aptitude");

        myGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(java.awt.Color.black);
        jRadioButton2.setText("Technical MCQs");

        myGroup1.add(jRadioButton3);
        jRadioButton3.setForeground(java.awt.Color.black);
        jRadioButton3.setText("Reasoning");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Log out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(java.awt.Color.black);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Instructions:\nStep 1: Select test\nStep 2: Answer all questions within 30 minutes\nStep 3: Submit to get score and start a new test\nAll the best!");
        jScrollPane1.setViewportView(jTextArea1);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setForeground(java.awt.Color.black);
        jRadioButton4.setVisible(false);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setForeground(java.awt.Color.black);
        jRadioButton5.setVisible(false);

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setForeground(java.awt.Color.black);
        jRadioButton6.setVisible(false);

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setForeground(java.awt.Color.black);
        jRadioButton7.setVisible(false);

        jButton3.setText("Next");
        jButton3.setVisible(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Submit test");
        jButton4.setVisible(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setVisible(false);

        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("0");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(":");

        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(106, 106, 106)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(54, 54, 54)
                                .addComponent(jRadioButton2)
                                .addGap(52, 52, 52)
                                .addComponent(jRadioButton3)
                                .addGap(64, 64, 64)
                                .addComponent(jButton1)
                                .addGap(64, 64, 64)
                                .addComponent(jButton2)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton5))
                        .addContainerGap(44, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(3, 3, 3)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jRadioButton4)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton5)
                .addGap(34, 34, 34)
                .addComponent(jRadioButton6)
                .addGap(41, 41, 41)
                .addComponent(jRadioButton7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        close1();
        LogIn n=new LogIn();
        n.setVisible(true);
         n.getContentPane().setBackground(new java.awt.Color(84,114,113));
    }//GEN-LAST:event_jButton2ActionPerformed
int min=1;
    int sec=1;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Enumeration<AbstractButton> allRadioButton=myGroup1.getElements();  
        while(allRadioButton.hasMoreElements())  
        {  
           JRadioButton temp12=(JRadioButton)allRadioButton.nextElement();  
           if(temp12.isSelected())  
           {  
             que_type=temp12.getText(); 
           }  
        }   
        switch (que_type) {
            case "null":
                jLabel1.setText("Please select test");
                break;
            case "Aptitude":
            {
                
                
                 t1=new Timer(60000,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                 //To change body of generated methods, choose Tools | Templates.
                 jLabel3.setText(""+min);
                 min++;
                 if(min==31)
        {
           t1.stop();
           t.stop();
            jButton3.setVisible(false);
            jLabel1.setText("Done, you scored: "+score);
        }
            }
        });
        t=new Timer(1000,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                 //To change body of generated methods, choose Tools | Templates.
                 jLabel5.setText(""+sec);
                 sec++;
                 if(sec==60)
        {
            sec=0;
        }
            }
        });
       t1.start();
        t.start();
                
                
                
                
                
                
                level=1;
                type="aptitude";
                    jLabel1.setText("");
                    jRadioButton1.setVisible(false);
                    jRadioButton2.setVisible(false);
                    jRadioButton3.setVisible(false);
                    jButton1.setVisible(false);
                    jButton2.setVisible(false);
                    jTextArea1.setText("");
                    jLabel2.setVisible(true);
                    jRadioButton4.setVisible(true);
                    jRadioButton5.setVisible(true);
                    jRadioButton6.setVisible(true);
                    jRadioButton7.setVisible(true);
                    jButton3.setVisible(true);
                    jButton4.setVisible(true);
                    
                    try
                    {
                        Class.forName("com.mysq.jdbc.Driver");
                    }
                    catch(Exception e)
                    {
                        
                    }  try
                    {
                        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mohan","root","Skype@123");
                         st=con.createStatement();
                        
                        
                        rs=st.executeQuery("SELECT * FROM medium WHERE qm_id="+aptmedium_id+"");
                        if(rs.next())
                        {
                            
                
                             q=rs.getString("quesm");
                            a=rs.getString("qm_a");
                             b=rs.getString("qm_b");
                             c=rs.getString("qm_c");
                             d=rs.getString("qm_d");
                             cor=rs.getString("qm_correct");
                             jLabel2.setText(""+(++number));
                            jTextArea1.setText(""+q);
                            jRadioButton4.setText(""+a);
                            jRadioButton5.setText(""+b);
                            jRadioButton6.setText(""+c);
                            jRadioButton7.setText(""+d);
                            
                        }
                        
                    }
                    catch(Exception e)
                    {
                        
                    }  break;
            }
            case "Technical MCQs":
            {
                
                
                 t1=new Timer(60000,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                 //To change body of generated methods, choose Tools | Templates.
                 jLabel3.setText(""+min);
                 min++;
                 if(min==31)
        {
           t1.stop();
           t.stop();
            jButton3.setVisible(false);
            jLabel1.setText("Done, you scored: "+score);
        }
            }
        });
        t=new Timer(1000,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                 //To change body of generated methods, choose Tools | Templates.
                 jLabel5.setText(""+sec);
                 sec++;
                 if(sec==60)
        {
            sec=0;
        }
            }
        });
       t1.start();
        t.start();
                
                
                
                
                
                level=1;
                type="technical";
                    jLabel1.setText("");
                    jRadioButton1.setVisible(false);
                    jRadioButton2.setVisible(false);
                    jRadioButton3.setVisible(false);
                    jButton1.setVisible(false);
                    jButton2.setVisible(false);
                    jTextArea1.setText("");
                    jLabel2.setVisible(true);
                    jRadioButton4.setVisible(true);
                    jRadioButton5.setVisible(true);
                    jRadioButton6.setVisible(true);
                    jRadioButton7.setVisible(true);
                    jButton3.setVisible(true);
                    jButton4.setVisible(true);
                    Connection con=null;
                    try
                    {
                        Class.forName("com.mysq.jdbc.Driver");
                    }
                    catch(Exception e)
                    {
                        
                    }  try
                    {
                        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mohan","root","Skype@123");
                         st=con.createStatement();
                        
                        rs=st.executeQuery("SELECT * FROM medium_t WHERE qtm_id="+techmedium_id+"");
                        if(rs.next())
                        {
                             q=rs.getString("questm");
                             a=rs.getString("qtm_a");
                             b=rs.getString("qtm_b");
                             c=rs.getString("qtm_c");
                             d=rs.getString("qtm_d");
                             cor=rs.getString("qtm_correct");
                             jLabel2.setText(""+(++number));
                            jTextArea1.setText(""+q);
                            jRadioButton4.setText(""+a);
                            jRadioButton5.setText(""+b);
                            jRadioButton6.setText(""+c);
                            jRadioButton7.setText(""+d);
                            
                        }
                    }
                    catch(Exception e)
                    {
                        
                    }  break;
            }
            default:
            {
                
                
                 t1=new Timer(60000,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                 //To change body of generated methods, choose Tools | Templates.
                 jLabel3.setText(""+min);
                 min++;
                 if(min==31)
        {
           t1.stop();
           t.stop();
            jButton3.setVisible(false);
            jLabel1.setText("Done, you scored: "+score);
        }
            }
        });
        t=new Timer(1000,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                 //To change body of generated methods, choose Tools | Templates.
                 jLabel5.setText(""+sec);
                 sec++;
                 if(sec==60)
        {
            sec=0;
        }
            }
        });
       t1.start();
        t.start();
                
                
                
                
                level=1;
                type="reasoning";
             jLabel1.setText("");
                    jRadioButton1.setVisible(false);
                    jRadioButton2.setVisible(false);
                    jRadioButton3.setVisible(false);
                    jButton1.setVisible(false);
                    jButton2.setVisible(false);
                    jTextArea1.setText("");
                    jLabel2.setVisible(true);
                    jRadioButton4.setVisible(true);
                    jRadioButton5.setVisible(true);
                    jRadioButton6.setVisible(true);
                    jRadioButton7.setVisible(true);
                    jButton3.setVisible(true);
                    jButton4.setVisible(true);
                    Connection con=null;
                    try
                    {
                        Class.forName("com.mysq.jdbc.Driver");
                    }
                    catch(Exception e)
                    {
                        
                    }  try
                    {
                        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mohan","root","Skype@123");
                         st=con.createStatement();
                        
                        rs=st.executeQuery("SELECT * FROM medium_r WHERE qrm_id="+reamedium_id+"");
                        if(rs.next())
                        {
                             q=rs.getString("quesrm");
                             a=rs.getString("qrm_a");
                             b=rs.getString("qrm_b");
                             c=rs.getString("qrm_c");
                             d=rs.getString("qrm_d");
                             cor=rs.getString("qrm_correct");
                             jLabel2.setText(""+(++number));
                            jTextArea1.setText(""+q);
                            jRadioButton4.setText(""+a);
                            jRadioButton5.setText(""+b);
                            jRadioButton6.setText(""+c);
                            jRadioButton7.setText(""+d);
                            
                        }
                    }
                    catch(Exception e)
                    {
                        
                    }  break;
            
                
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       /* jTextArea1.setVisible(false);
        jRadioButton4.setVisible(false);
        jRadioButton5.setVisible(false);
        jRadioButton6.setVisible(false);
        jRadioButton7.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);*/
       jButton3.setVisible(false);
      t.stop();
      t1.stop();
       jLabel1.setText("Done, you scored: "+score);
        try
        {
            Class.forName("com.mysq.jdbc.Driver");
        }
        catch(Exception e)
        {
            
        }
         try
        {
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mohan","root","Skype@123");
           PreparedStatement st;
           st=con.prepareStatement("INSERT INTO record(name,score,test) VALUES(?,?,?)");
           st.setString(1,user);
           st.setInt(2,score);
           st.setString(3,que_type);
           st.executeUpdate();
        }
        catch(Exception e)
        {
            
        }

       try{
            con.close();
        }
        catch(Exception e)
        {
            
        }
       jLabel3.setText(""+0);
       jLabel5.setText(""+0);
       min=1;
       sec=1;
       apteasy_id=0;
       aptmedium_id=1;
       apthard_id=0;
       techeasy_id=0;
       techmedium_id=1;
       techhard_id=0;
       reaeasy_id=0;
       reamedium_id=1;
       reahard_id=0;
       score=0;
       number=0;
       jTextArea1.setText("Select test");
       jRadioButton4.setText("Select test");
       jRadioButton5.setText("Select test");
        jRadioButton6.setText("Select test");
        jRadioButton7.setText("Select test");
        jLabel2.setText("");
        jRadioButton1.setVisible(true);
            jRadioButton2.setVisible(true);
            jRadioButton3.setVisible(true);
            jButton1.setVisible(true);
            jButton2.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       if(que_type.equals("Aptitude"))
       {
           if(number!=30)
           {
                Enumeration<AbstractButton> allRadioButton=buttonGroup1.getElements();
                while(allRadioButton.hasMoreElements())
                {
                    JRadioButton temp21=(JRadioButton)allRadioButton.nextElement();
                    if(temp21.isSelected())
                    {
                        selected=temp21.getText();
                    }
                }      
                
                if(selected!=null)
                {
                 if(selected.equals(cor))
                {
                    score++;
                    
                    try
                    {
                        Class.forName("com.mysq.jdbc.Driver");
                    }
                    catch(Exception e)
                    {
                        
                    } 
                    try
                    {
                        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mohan","root","Skype@123");
                         st=con.createStatement();
                        
                        if(level==1 || level==2)
                        {
                            level=2;
                            
                            int temp=++apthard_id;
                            rs=st.executeQuery("SELECT * FROM hard WHERE qh_id="+temp+"");
                            if(rs.next())
                            {
                                
                                q=rs.getString("quesh");
                                a=rs.getString("qh_a");
                                b=rs.getString("qh_b");
                                c=rs.getString("qh_c");
                                d=rs.getString("qh_d");
                                cor=rs.getString("qh_correct");
                                jLabel2.setText(""+(++number));
                                jTextArea1.setText(""+q);
                                jRadioButton4.setText(""+a);
                                jRadioButton5.setText(""+b);
                                jRadioButton6.setText(""+c);
                                jRadioButton7.setText(""+d);
                                 jLabel1.setText("");
                            }
                           else
                            {
                                jButton3.setVisible(false);
                                jLabel1.setText("Done, you scored: "+score);
                            }
                        }
                        else
                        {
                            level=1;
                            
                            int temp=++aptmedium_id;
                            rs=st.executeQuery("SELECT * FROM medium WHERE qm_id="+temp+"");
                            if(rs.next())
                            {
                                
                                q=rs.getString("quesm");
                                a=rs.getString("qm_a");
                                b=rs.getString("qm_b");
                                c=rs.getString("qm_c");
                                d=rs.getString("qm_d");
                                cor=rs.getString("qm_correct");
                                jLabel2.setText(""+(++number));
                                jTextArea1.setText(""+q);
                                jRadioButton4.setText(""+a);
                                jRadioButton5.setText(""+b);
                                jRadioButton6.setText(""+c);
                                jRadioButton7.setText(""+d);
                                jLabel1.setText("");
                            }
                            else
                            {
                                jButton3.setVisible(false);
                                jLabel1.setText("Done, you scored: "+score);
                            }
                            
                        }
                    }
                    catch(Exception e)
                    {
                        
                    }
                    
                    
                }
                else
                {
                    
                    try
                    {
                        Class.forName("com.mysq.jdbc.Driver");
                    }
                    catch(Exception e)
                    {
                        
                    }
                    try
                    {
                        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mohan","root","Skype@123");
                         st=con.createStatement();
                       
                        if(level==0 || level==1)
                        {
                            int temp=++apteasy_id;
                            rs=st.executeQuery("SELECT * FROM easy WHERE q_id="+temp+"");
                            if(rs.next())
                            {
                                level=0;
                                q=rs.getString("ques");
                                a=rs.getString("q_a");
                                b=rs.getString("q_b");
                                c=rs.getString("q_c");
                                d=rs.getString("q_d");
                                cor=rs.getString("q_correct");
                                jLabel2.setText(""+(++number));
                                jTextArea1.setText(""+q);
                                jRadioButton4.setText(""+a);
                                jRadioButton5.setText(""+b);
                                jRadioButton6.setText(""+c);
                                jRadioButton7.setText(""+d);
                                jLabel1.setText("");
                            }
                            
                            else
                            {
                                jButton3.setVisible(false);
                                jLabel1.setText("Done, you scored: "+score);
                            }
                        }
                        else
                        {
                            int temp=++aptmedium_id;
                            rs=st.executeQuery("SELECT * FROM medium WHERE qm_id="+temp+"");
                            if(rs.next())
                            {
                                level=1;
                                q=rs.getString("quesm");
                                a=rs.getString("qm_a");
                                b=rs.getString("qm_b");
                                c=rs.getString("qm_c");
                                d=rs.getString("qm_d");
                                cor=rs.getString("qm_correct");
                                jLabel2.setText(""+(++number));
                                jTextArea1.setText(""+q);
                                jRadioButton4.setText(""+a);
                                jRadioButton5.setText(""+b);
                                jRadioButton6.setText(""+c);
                                jRadioButton7.setText(""+d);
                                jLabel1.setText("");
                            }
                            else
                            {
                                jButton3.setVisible(false);
                                jLabel1.setText("Done, you scored: "+score);
                            }
                        }
                    }
                    catch(Exception e)
                    {
                        
                    }
                }
                }
                else
                {
                    jLabel1.setText("Please select an option");
                }
       }
           else
           {
               jButton3.setVisible(false);
                                jLabel1.setText("Done, you scored: "+(++score));
           }
       }
       else if(que_type.equals("Technical MCQs"))
       {
           if(number!=30)
           {
            Enumeration<AbstractButton> allRadioButton=buttonGroup1.getElements();
                while(allRadioButton.hasMoreElements())
                {
                    JRadioButton temp21=(JRadioButton)allRadioButton.nextElement();
                    if(temp21.isSelected())
                    {
                        selected=temp21.getText();
                    }
                }      
                
                if(selected!=null)
                {
                 if(selected.equals(cor))
                {
                    score++;
                    
                    try
                    {
                        Class.forName("com.mysq.jdbc.Driver");
                    }
                    catch(Exception e)
                    {
                        
                    } 
                    try
                    {
                        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mohan","root","Skype@123");
                         st=con.createStatement();
                        
                        if(level==1 || level==2)
                        {
                            level=2;
                            
                            int temp=++techhard_id;
                            rs=st.executeQuery("SELECT * FROM hard_t WHERE qth_id="+temp+"");
                            if(rs.next())
                            {
                                
                                q=rs.getString("questh");
                                a=rs.getString("qth_a");
                                b=rs.getString("qth_b");
                                c=rs.getString("qth_c");
                                d=rs.getString("qth_d");
                                cor=rs.getString("qth_correct");
                                jLabel2.setText(""+(++number));
                                jTextArea1.setText(""+q);
                                jRadioButton4.setText(""+a);
                                jRadioButton5.setText(""+b);
                                jRadioButton6.setText(""+c);
                                jRadioButton7.setText(""+d);
                                jLabel1.setText("");
                            }
                           else
                            {
                                jButton3.setVisible(false);
                                jLabel1.setText("Done, you scored: "+score);
                            }
                        }
                        else
                        {
                            level=1;
                            
                            int temp=++techmedium_id;
                            rs=st.executeQuery("SELECT * FROM medium_t WHERE qtm_id="+temp+"");
                            if(rs.next())
                            {
                                
                                q=rs.getString("questm");
                                a=rs.getString("qtm_a");
                                b=rs.getString("qtm_b");
                                c=rs.getString("qtm_c");
                                d=rs.getString("qtm_d");
                                cor=rs.getString("qtm_correct");
                                jLabel2.setText(""+(++number));
                                jTextArea1.setText(""+q);
                                jRadioButton4.setText(""+a);
                                jRadioButton5.setText(""+b);
                                jRadioButton6.setText(""+c);
                                jRadioButton7.setText(""+d);
                                jLabel1.setText("");
                            }
                            else
                            {
                                jButton3.setVisible(false);
                                jLabel1.setText("Done, you scored: "+score);
                            }
                            
                        }
                    }
                    catch(Exception e)
                    {
                        
                    }
                    
                    
                }
                else
                {
                    
                    try
                    {
                        Class.forName("com.mysq.jdbc.Driver");
                    }
                    catch(Exception e)
                    {
                        
                    }
                    try
                    {
                        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mohan","root","Skype@123");
                         st=con.createStatement();
                       
                        if(level==0 || level==1)
                        {
                            int temp=++techeasy_id;
                            rs=st.executeQuery("SELECT * FROM easy_t WHERE qt_id="+temp+"");
                            if(rs.next())
                            {
                                level=0;
                                q=rs.getString("quest");
                                a=rs.getString("qt_a");
                                b=rs.getString("qt_b");
                                c=rs.getString("qt_c");
                                d=rs.getString("qt_d");
                                cor=rs.getString("qt_correct");
                                jLabel2.setText(""+(++number));
                                jTextArea1.setText(""+q);
                                jRadioButton4.setText(""+a);
                                jRadioButton5.setText(""+b);
                                jRadioButton6.setText(""+c);
                                jRadioButton7.setText(""+d);
                                jLabel1.setText("");
                            }
                            
                            else
                            {
                                jButton3.setVisible(false);
                                jLabel1.setText("Done, you scored: "+score);
                            }
                        }
                        else
                        {
                            int temp=++techmedium_id;
                            rs=st.executeQuery("SELECT * FROM medium_t WHERE qtm_id="+temp+"");
                            if(rs.next())
                            {
                                level=1;
                                q=rs.getString("questm");
                                a=rs.getString("qtm_a");
                                b=rs.getString("qtm_b");
                                c=rs.getString("qtm_c");
                                d=rs.getString("qtm_d");
                                cor=rs.getString("qtm_correct");
                                jLabel2.setText(""+(++number));
                                jTextArea1.setText(""+q);
                                jRadioButton4.setText(""+a);
                                jRadioButton5.setText(""+b);
                                jRadioButton6.setText(""+c);
                                jRadioButton7.setText(""+d);
                                jLabel1.setText("");
                            }
                            else
                            {
                                jButton3.setVisible(false);
                                jLabel1.setText("Done, you scored: "+score);
                            }
                        }
                    }
                    catch(Exception e)
                    {
                        
                    }
                }
                }
                else
                {
                    jLabel1.setText("Please select an option");
                }
       }     
                else
           {
               jButton3.setVisible(false);
                                jLabel1.setText("Done, you scored: "+(++score));
           }
           
       }
       else
       {
           if(number!=30)
           {
            Enumeration<AbstractButton> allRadioButton=buttonGroup1.getElements();
                while(allRadioButton.hasMoreElements())
                {
                    JRadioButton temp21=(JRadioButton)allRadioButton.nextElement();
                    if(temp21.isSelected())
                    {
                        selected=temp21.getText();
                    }
                }      
                
                if(selected!=null)
                {
                 if(selected.equals(cor))
                {
                    score++;
                    
                    try
                    {
                        Class.forName("com.mysq.jdbc.Driver");
                    }
                    catch(Exception e)
                    {
                        
                    } 
                    try
                    {
                        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mohan","root","Skype@123");
                         st=con.createStatement();
                        
                        if(level==1 || level==2)
                        {
                            level=2;
                            
                            int temp=++reahard_id;
                            rs=st.executeQuery("SELECT * FROM hard_r WHERE qrh_id="+temp+"");
                            if(rs.next())
                            {
                                
                                q=rs.getString("quesrh");
                                a=rs.getString("qrh_a");
                                b=rs.getString("qrh_b");
                                c=rs.getString("qrh_c");
                                d=rs.getString("qrh_d");
                                cor=rs.getString("qrh_correct");
                                jLabel2.setText(""+(++number));
                                jTextArea1.setText(""+q);
                                jRadioButton4.setText(""+a);
                                jRadioButton5.setText(""+b);
                                jRadioButton6.setText(""+c);
                                jRadioButton7.setText(""+d);
                                jLabel1.setText("");
                            }
                           else
                            {
                                jButton3.setVisible(false);
                                jLabel1.setText("Done, you scored: "+score);
                            }
                        }
                        else
                        {
                            level=1;
                            
                            int temp=++reamedium_id;
                            rs=st.executeQuery("SELECT * FROM medium_r WHERE qrm_id="+temp+"");
                            if(rs.next())
                            {
                                
                                q=rs.getString("quesrm");
                                a=rs.getString("qrm_a");
                                b=rs.getString("qrm_b");
                                c=rs.getString("qrm_c");
                                d=rs.getString("qrm_d");
                                cor=rs.getString("qrm_correct");
                                jLabel2.setText(""+(++number));
                                jTextArea1.setText(""+q);
                                jRadioButton4.setText(""+a);
                                jRadioButton5.setText(""+b);
                                jRadioButton6.setText(""+c);
                                jRadioButton7.setText(""+d);
                                jLabel1.setText("");
                            }
                            else
                            {
                                jButton3.setVisible(false);
                                jLabel1.setText("Done, you scored: "+score);
                            }
                            
                        }
                    }
                    catch(Exception e)
                    {
                        
                    }
                    
                    
                }
                else
                {
                    
                    try
                    {
                        Class.forName("com.mysq.jdbc.Driver");
                    }
                    catch(Exception e)
                    {
                        
                    }
                    try
                    {
                        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mohan","root","Skype@123");
                         st=con.createStatement();
                       
                        if(level==0 || level==1)
                        {
                            int temp=++reaeasy_id;
                            rs=st.executeQuery("SELECT * FROM easy_r WHERE qr_id="+temp+"");
                            if(rs.next())
                            {
                                level=0;
                                q=rs.getString("quesr");
                                a=rs.getString("qr_a");
                                b=rs.getString("qr_b");
                                c=rs.getString("qr_c");
                                d=rs.getString("qr_d");
                                cor=rs.getString("qr_correct");
                                jLabel2.setText(""+(++number));
                                jTextArea1.setText(""+q);
                                jRadioButton4.setText(""+a);
                                jRadioButton5.setText(""+b);
                                jRadioButton6.setText(""+c);
                                jRadioButton7.setText(""+d);
                                jLabel1.setText("");
                            }
                            
                            else
                            {
                                jButton3.setVisible(false);
                                jLabel1.setText("Done, you scored: "+score);
                            }
                        }
                        else
                        {
                            int temp=++reamedium_id;
                            rs=st.executeQuery("SELECT * FROM medium_r WHERE qrm_id="+temp+"");
                            if(rs.next())
                            {
                                level=1;
                                q=rs.getString("quesrm");
                                a=rs.getString("qrm_a");
                                b=rs.getString("qrm_b");
                                c=rs.getString("qrm_c");
                                d=rs.getString("qrm_d");
                                cor=rs.getString("qrm_correct");
                                jLabel2.setText(""+(++number));
                                jTextArea1.setText(""+q);
                                jRadioButton4.setText(""+a);
                                jRadioButton5.setText(""+b);
                                jRadioButton6.setText(""+c);
                                jRadioButton7.setText(""+d);
                                jLabel1.setText("");
                            }
                            else
                            {
                                jButton3.setVisible(false);
                                jLabel1.setText("Done, you scored: "+score);
                            }
                        }
                    }
                    catch(Exception e)
                    {
                        
                    }
                }
                }
                else
                {
                    jLabel1.setText("Please select an option");
                }
       }
           else
           {
               jButton3.setVisible(false);
                                jLabel1.setText("Done, you scored: "+(++score));
           }
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.ButtonGroup myGroup1;
    private javax.swing.ButtonGroup myGroup2;
    // End of variables declaration//GEN-END:variables
}
